# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\s\Desktop\doc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1482, 804)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sidebar_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_2.sizePolicy().hasHeightForWidth())
        self.sidebar_2.setSizePolicy(sizePolicy)
        self.sidebar_2.setStyleSheet("* {\n"
"    background-color:rgb(245, 245, 245);\n"
"    font: 16pt \"Bell MT\";\n"
"    border-bottom-right-radius:4px;\n"
"    border-top-right-radius:4px;\n"
"}\n"
"QPushButton{\n"
"    text-align: left;\n"
"    border:none;\n"
"    height: 54px;\n"
"    padding-left: 10px;\n"
"    border-radius:8px;\n"
"    cursor: pointer;\n"
"}\n"
"QLabel{\n"
"    font: 17pt \"Bell MT\";\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8794ac;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.sidebar_2.setObjectName("sidebar_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sidebar_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.app_logo_2 = QtWidgets.QLabel(self.sidebar_2)
        self.app_logo_2.setStyleSheet("")
        self.app_logo_2.setText("")
        self.app_logo_2.setPixmap(QtGui.QPixmap(":/images/images/images/doctor.png"))
        self.app_logo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.app_logo_2.setObjectName("app_logo_2")
        self.verticalLayout_4.addWidget(self.app_logo_2)
        self.hide_btn_2 = QtWidgets.QPushButton(self.sidebar_2)
        self.hide_btn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-menu-bar-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hide_btn_2.setIcon(icon)
        self.hide_btn_2.setIconSize(QtCore.QSize(22, 22))
        self.hide_btn_2.setCheckable(True)
        self.hide_btn_2.setAutoExclusive(False)
        self.hide_btn_2.setObjectName("hide_btn_2")
        self.verticalLayout_4.addWidget(self.hide_btn_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn_2 = QtWidgets.QPushButton(self.sidebar_2)
        self.home_btn_2.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.home_btn_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-home-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_2.setIcon(icon1)
        self.home_btn_2.setIconSize(QtCore.QSize(22, 22))
        self.home_btn_2.setCheckable(True)
        self.home_btn_2.setAutoExclusive(True)
        self.home_btn_2.setObjectName("home_btn_2")
        self.verticalLayout_2.addWidget(self.home_btn_2)
        self.search_btn_2 = QtWidgets.QPushButton(self.sidebar_2)
        self.search_btn_2.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.search_btn_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-search-65.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn_2.setIcon(icon2)
        self.search_btn_2.setIconSize(QtCore.QSize(22, 22))
        self.search_btn_2.setCheckable(True)
        self.search_btn_2.setAutoExclusive(True)
        self.search_btn_2.setObjectName("search_btn_2")
        self.verticalLayout_2.addWidget(self.search_btn_2)
        self.request_btn_2 = QtWidgets.QPushButton(self.sidebar_2)
        self.request_btn_2.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.request_btn_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-doctor-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.request_btn_2.setIcon(icon3)
        self.request_btn_2.setIconSize(QtCore.QSize(22, 22))
        self.request_btn_2.setCheckable(True)
        self.request_btn_2.setAutoExclusive(True)
        self.request_btn_2.setObjectName("request_btn_2")
        self.verticalLayout_2.addWidget(self.request_btn_2)
        self.record_btn_2 = QtWidgets.QPushButton(self.sidebar_2)
        self.record_btn_2.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.record_btn_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-history-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.record_btn_2.setIcon(icon4)
        self.record_btn_2.setIconSize(QtCore.QSize(22, 22))
        self.record_btn_2.setCheckable(True)
        self.record_btn_2.setAutoExclusive(True)
        self.record_btn_2.setObjectName("record_btn_2")
        self.verticalLayout_2.addWidget(self.record_btn_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.profile_btn_2 = QtWidgets.QPushButton(self.sidebar_2)
        self.profile_btn_2.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.profile_btn_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-admin-settings-male-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_btn_2.setIcon(icon5)
        self.profile_btn_2.setIconSize(QtCore.QSize(22, 22))
        self.profile_btn_2.setCheckable(True)
        self.profile_btn_2.setAutoExclusive(True)
        self.profile_btn_2.setObjectName("profile_btn_2")
        self.verticalLayout_2.addWidget(self.profile_btn_2)
        self.quit_btn_2 = QtWidgets.QPushButton(self.sidebar_2)
        self.quit_btn_2.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.quit_btn_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\s\\Desktop\\calladoc/images/icons/icons8-logout-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit_btn_2.setIcon(icon6)
        self.quit_btn_2.setIconSize(QtCore.QSize(22, 22))
        self.quit_btn_2.setCheckable(True)
        self.quit_btn_2.setAutoExclusive(True)
        self.quit_btn_2.setObjectName("quit_btn_2")
        self.verticalLayout_2.addWidget(self.quit_btn_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.sidebar_2, 0, 0, 1, 1)
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setStyleSheet("* {\n"
"    background-color:rgb(245, 245, 245);\n"
"    font: 16pt \"Bell MT\";\n"
"    border-bottom-right-radius:4px;\n"
"    border-top-right-radius:4px;\n"
"}\n"
"QPushButton{\n"
"    text-align: left;\n"
"    border:none;\n"
"    height: 54px;\n"
"    padding-left: 10px;\n"
"    border-top-left-radius:8px;\n"
"    border-bottom-left-radius:8px;\n"
"    border-top-right-radius:8px;\n"
"    border-bottom-right-radius:8px;\n"
"    cursor: pointer;\n"
"}\n"
"QLabel{\n"
"    font: 17pt \"Bell MT\";\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8794ac;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_logo = QtWidgets.QLabel(self.sidebar)
        self.app_logo.setStyleSheet("")
        self.app_logo.setText("")
        self.app_logo.setPixmap(QtGui.QPixmap(":/images/images/images/doctor.png"))
        self.app_logo.setObjectName("app_logo")
        self.horizontalLayout.addWidget(self.app_logo)
        self.app_name = QtWidgets.QLabel(self.sidebar)
        self.app_name.setObjectName("app_name")
        self.horizontalLayout.addWidget(self.app_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hide_btn = QtWidgets.QPushButton(self.sidebar)
        self.hide_btn.setStyleSheet("QPushButton:checked{\n"
"}")
        self.hide_btn.setIcon(icon)
        self.hide_btn.setIconSize(QtCore.QSize(22, 22))
        self.hide_btn.setCheckable(True)
        self.hide_btn.setAutoExclusive(False)
        self.hide_btn.setObjectName("hide_btn")
        self.verticalLayout.addWidget(self.hide_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.home_btn = QtWidgets.QPushButton(self.sidebar)
        self.home_btn.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.home_btn.setIcon(icon1)
        self.home_btn.setIconSize(QtCore.QSize(22, 22))
        self.home_btn.setCheckable(True)
        self.home_btn.setAutoExclusive(True)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout_3.addWidget(self.home_btn)
        self.search_btn = QtWidgets.QPushButton(self.sidebar)
        self.search_btn.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.search_btn.setIcon(icon2)
        self.search_btn.setIconSize(QtCore.QSize(22, 22))
        self.search_btn.setCheckable(True)
        self.search_btn.setAutoExclusive(True)
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout_3.addWidget(self.search_btn)
        self.request_btn = QtWidgets.QPushButton(self.sidebar)
        self.request_btn.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.request_btn.setIcon(icon3)
        self.request_btn.setIconSize(QtCore.QSize(22, 22))
        self.request_btn.setCheckable(True)
        self.request_btn.setAutoExclusive(True)
        self.request_btn.setObjectName("request_btn")
        self.verticalLayout_3.addWidget(self.request_btn)
        self.record_btn = QtWidgets.QPushButton(self.sidebar)
        self.record_btn.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.record_btn.setIcon(icon4)
        self.record_btn.setIconSize(QtCore.QSize(22, 22))
        self.record_btn.setCheckable(True)
        self.record_btn.setAutoExclusive(True)
        self.record_btn.setObjectName("record_btn")
        self.verticalLayout_3.addWidget(self.record_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.profile_btn = QtWidgets.QPushButton(self.sidebar)
        self.profile_btn.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.profile_btn.setIcon(icon5)
        self.profile_btn.setIconSize(QtCore.QSize(22, 22))
        self.profile_btn.setCheckable(True)
        self.profile_btn.setAutoExclusive(True)
        self.profile_btn.setObjectName("profile_btn")
        self.verticalLayout_3.addWidget(self.profile_btn)
        self.quit_btn = QtWidgets.QPushButton(self.sidebar)
        self.quit_btn.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(63,97,132);\n"
"    color:rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-logout-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit_btn.setIcon(icon7)
        self.quit_btn.setIconSize(QtCore.QSize(22, 22))
        self.quit_btn.setCheckable(True)
        self.quit_btn.setAutoExclusive(True)
        self.quit_btn.setObjectName("quit_btn")
        self.verticalLayout_3.addWidget(self.quit_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.sidebar, 0, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_6)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("background-color: rgb(229, 229, 241);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_pg = QtWidgets.QWidget()
        self.home_pg.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.477091, x2:1, y2:0.494, stop:0 rgba(47, 0, 116, 255), stop:1 rgba(255, 212, 212, 255));")
        self.home_pg.setObjectName("home_pg")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.home_pg)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.dark_bg = QtWidgets.QWidget(self.home_pg)
        self.dark_bg.setStyleSheet("background-color: rgba(0, 0, 0, 128);\n"
"")
        self.dark_bg.setObjectName("dark_bg")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.dark_bg)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(20)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(-1, 40, -1, -1)
        self.verticalLayout_21.setSpacing(10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.home_header_3 = QtWidgets.QLabel(self.dark_bg)
        self.home_header_3.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.home_header_3.setAlignment(QtCore.Qt.AlignCenter)
        self.home_header_3.setObjectName("home_header_3")
        self.verticalLayout_21.addWidget(self.home_header_3)
        self.home_header_4 = QtWidgets.QLabel(self.dark_bg)
        self.home_header_4.setStyleSheet("background-color: transparent;\n"
"font: 75 20pt \"Bell MT\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.home_header_4.setAlignment(QtCore.Qt.AlignCenter)
        self.home_header_4.setObjectName("home_header_4")
        self.verticalLayout_21.addWidget(self.home_header_4)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.about_2 = QtWidgets.QWidget(self.dark_bg)
        self.about_2.setStyleSheet("background-color:#02007a;\n"
"border-radius:4px;")
        self.about_2.setObjectName("about_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.about_2)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(50, 50, 100, 0)
        self.verticalLayout_19.setSpacing(10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.about_us_2 = QtWidgets.QLabel(self.about_2)
        self.about_us_2.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.about_us_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.about_us_2.setObjectName("about_us_2")
        self.verticalLayout_19.addWidget(self.about_us_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.about_2)
        self.textEdit_2.setStyleSheet("background-color: transparent;\n"
"font: 18pt \"Bell MT\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_19.addWidget(self.textEdit_2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_19)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.label_3 = QtWidgets.QLabel(self.about_2)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/images/images/doctor1.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.verticalLayout_20.addWidget(self.about_2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ourpartner_2 = QtWidgets.QLabel(self.dark_bg)
        self.ourpartner_2.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.ourpartner_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ourpartner_2.setObjectName("ourpartner_2")
        self.verticalLayout_10.addWidget(self.ourpartner_2)
        self.label_2 = QtWidgets.QLabel(self.dark_bg)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/images/images/PyDracula.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.verticalLayout_20.addLayout(self.verticalLayout_10)
        self.verticalLayout_22.addLayout(self.verticalLayout_20)
        self.gridLayout_14.addLayout(self.verticalLayout_22, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.dark_bg, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.home_pg)
        self.search_pg = QtWidgets.QWidget()
        self.search_pg.setStyleSheet("")
        self.search_pg.setObjectName("search_pg")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.search_pg)
        self.gridLayout_12.setContentsMargins(-1, 25, -1, -1)
        self.gridLayout_12.setVerticalSpacing(20)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_3 = QtWidgets.QWidget(self.search_pg)
        self.widget_3.setStyleSheet("background-color: rgb(2, 0, 122);\n"
"    border-radius: 8px;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_9.setContentsMargins(50, 30, 50, 40)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.search_table = QtWidgets.QTableWidget(self.widget_3)
        self.search_table.setStyleSheet("QHeaderView:section{\n"
"        \n"
"    background-color: rgb(229, 229, 241);\n"
"}\n"
"QTableWidget{\n"
"background:transparent;\n"
"    background-color: rgb(255, 255, 255);\n"
"    alternate-background-color: rgb(229, 229, 241);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.search_table.setAlternatingRowColors(True)
        self.search_table.setRowCount(0)
        self.search_table.setObjectName("search_table")
        self.search_table.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_table.setHorizontalHeaderItem(1, item)
        self.search_table.horizontalHeader().setCascadingSectionResizes(False)
        self.search_table.horizontalHeader().setDefaultSectionSize(40)
        self.search_table.horizontalHeader().setStretchLastSection(True)
        self.search_table.verticalHeader().setVisible(False)
        self.search_table.verticalHeader().setCascadingSectionResizes(False)
        self.search_table.verticalHeader().setHighlightSections(True)
        self.gridLayout_9.addWidget(self.search_table, 1, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(100, -1, 100, 20)
        self.verticalLayout_9.setSpacing(50)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(50)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.search_lineedit_6 = QtWidgets.QLineEdit(self.widget_3)
        self.search_lineedit_6.setStyleSheet("\n"
"    font:  16pt \"Bell MT\";\n"
"    color: black;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;")
        self.search_lineedit_6.setText("")
        self.search_lineedit_6.setObjectName("search_lineedit_6")
        self.horizontalLayout_9.addWidget(self.search_lineedit_6)
        self.searchlinic_btn_6 = QtWidgets.QPushButton(self.widget_3)
        self.searchlinic_btn_6.setStyleSheet("background-color: transparent;")
        self.searchlinic_btn_6.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-search-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchlinic_btn_6.setIcon(icon8)
        self.searchlinic_btn_6.setIconSize(QtCore.QSize(25, 25))
        self.searchlinic_btn_6.setObjectName("searchlinic_btn_6")
        self.horizontalLayout_9.addWidget(self.searchlinic_btn_6)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.location_combobox = QtWidgets.QComboBox(self.widget_3)
        self.location_combobox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  16pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:4px;")
        self.location_combobox.setObjectName("location_combobox")
        self.horizontalLayout_10.addWidget(self.location_combobox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.gridLayout_9.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_3, 1, 0, 1, 1)
        self.request_header_2 = QtWidgets.QLabel(self.search_pg)
        self.request_header_2.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"font-weight:bold;")
        self.request_header_2.setAlignment(QtCore.Qt.AlignCenter)
        self.request_header_2.setObjectName("request_header_2")
        self.gridLayout_12.addWidget(self.request_header_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_pg)
        self.request_pg = QtWidgets.QWidget()
        self.request_pg.setObjectName("request_pg")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.request_pg)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.request_header = QtWidgets.QLabel(self.request_pg)
        self.request_header.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"font-weight:bold;")
        self.request_header.setAlignment(QtCore.Qt.AlignCenter)
        self.request_header.setObjectName("request_header")
        self.verticalLayout_12.addWidget(self.request_header)
        self.request_box = QtWidgets.QWidget(self.request_pg)
        self.request_box.setStyleSheet("background-color:#02007a;\n"
"border-radius:4px;")
        self.request_box.setObjectName("request_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.request_box)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(50, 30, 50, 50)
        self.verticalLayout_8.setSpacing(30)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.request_boxheader = QtWidgets.QLabel(self.request_box)
        self.request_boxheader.setStyleSheet("background-color: transparent;\n"
"font: 75 20pt \"Bell MT\";\n"
"color: white;\n"
"font-weight:bold;")
        self.request_boxheader.setAlignment(QtCore.Qt.AlignCenter)
        self.request_boxheader.setObjectName("request_boxheader")
        self.verticalLayout_8.addWidget(self.request_boxheader)
        self.clinic_combobox = QtWidgets.QComboBox(self.request_box)
        self.clinic_combobox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  16pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:4px;")
        self.clinic_combobox.setEditable(False)
        self.clinic_combobox.setObjectName("clinic_combobox")
        self.verticalLayout_8.addWidget(self.clinic_combobox)
        self.request_widget = QtWidgets.QWidget(self.request_box)
        self.request_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.request_widget.setObjectName("request_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.request_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_4.setSpacing(80)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date_label = QtWidgets.QLabel(self.request_widget)
        self.date_label.setStyleSheet("background-color: transparent;\n"
"font: 20pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_2.addWidget(self.date_label)
        self.dateEdit = QtWidgets.QDateEdit(self.request_widget)
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  20pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(40, 40, 40);")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time_label = QtWidgets.QLabel(self.request_widget)
        self.time_label.setStyleSheet("background-color: transparent;\n"
"font: 20pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_3.addWidget(self.time_label)
        self.timeEdit = QtWidgets.QTimeEdit(self.request_widget)
        self.timeEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  20pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(40, 40, 40);")
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_3.addWidget(self.timeEdit)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.requestdoctor_btn = QtWidgets.QPushButton(self.request_widget)
        self.requestdoctor_btn.setStyleSheet("\n"
"    border-radius:8px;\n"
"    font: bold 20pt \"Bell MT\";\n"
"    border:1px solid grey;\n"
"    background-color:#02007a;\n"
"    color: rgb(255, 255, 255);\n"
"")
        self.requestdoctor_btn.setObjectName("requestdoctor_btn")
        self.horizontalLayout_4.addWidget(self.requestdoctor_btn)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.request_widget)
        self.gridLayout_6.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.request_box)
        self.gridLayout_7.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(100, 0, 100, -1)
        self.horizontalLayout_5.setSpacing(100)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.day = QtWidgets.QWidget(self.request_pg)
        self.day.setStyleSheet("background-color:#02007a;\n"
"border-radius:30px;\n"
"")
        self.day.setObjectName("day")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.day)
        self.gridLayout_8.setContentsMargins(50, -1, 0, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_13.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.day)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/images/images/images/sun.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.day)
        self.label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dayprice_label = QtWidgets.QLabel(self.day)
        self.dayprice_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.dayprice_label.setObjectName("dayprice_label")
        self.horizontalLayout_8.addWidget(self.dayprice_label)
        self.day_price = QtWidgets.QLabel(self.day)
        self.day_price.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.day_price.setObjectName("day_price")
        self.horizontalLayout_8.addWidget(self.day_price)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.daystarttime_box = QtWidgets.QHBoxLayout()
        self.daystarttime_box.setSpacing(0)
        self.daystarttime_box.setObjectName("daystarttime_box")
        self.daystarttime_label = QtWidgets.QLabel(self.day)
        self.daystarttime_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.daystarttime_label.setObjectName("daystarttime_label")
        self.daystarttime_box.addWidget(self.daystarttime_label)
        self.daystarttime = QtWidgets.QLabel(self.day)
        self.daystarttime.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.daystarttime.setObjectName("daystarttime")
        self.daystarttime_box.addWidget(self.daystarttime)
        self.verticalLayout_11.addLayout(self.daystarttime_box)
        self.dayendtime_box = QtWidgets.QHBoxLayout()
        self.dayendtime_box.setSpacing(0)
        self.dayendtime_box.setObjectName("dayendtime_box")
        self.dayendtime_label = QtWidgets.QLabel(self.day)
        self.dayendtime_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.dayendtime_label.setObjectName("dayendtime_label")
        self.dayendtime_box.addWidget(self.dayendtime_label)
        self.dayendtime = QtWidgets.QLabel(self.day)
        self.dayendtime.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.dayendtime.setObjectName("dayendtime")
        self.dayendtime_box.addWidget(self.dayendtime)
        self.verticalLayout_11.addLayout(self.dayendtime_box)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.gridLayout_8.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.day)
        self.night = QtWidgets.QWidget(self.request_pg)
        self.night.setStyleSheet("background-color:#02007a;\n"
"border-radius:30px;\n"
"")
        self.night.setObjectName("night")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.night)
        self.gridLayout_10.setContentsMargins(50, -1, -1, -1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.night)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/images/images/images/moon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_15.addWidget(self.label_5)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.night)
        self.label_8.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.nightprice_label = QtWidgets.QLabel(self.night)
        self.nightprice_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.nightprice_label.setObjectName("nightprice_label")
        self.horizontalLayout_7.addWidget(self.nightprice_label)
        self.nightprice = QtWidgets.QLabel(self.night)
        self.nightprice.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.nightprice.setObjectName("nightprice")
        self.horizontalLayout_7.addWidget(self.nightprice)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.nightstarttime_box = QtWidgets.QHBoxLayout()
        self.nightstarttime_box.setSpacing(0)
        self.nightstarttime_box.setObjectName("nightstarttime_box")
        self.nightstarttime_label = QtWidgets.QLabel(self.night)
        self.nightstarttime_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.nightstarttime_label.setObjectName("nightstarttime_label")
        self.nightstarttime_box.addWidget(self.nightstarttime_label)
        self.nightstarttime = QtWidgets.QLabel(self.night)
        self.nightstarttime.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.nightstarttime.setObjectName("nightstarttime")
        self.nightstarttime_box.addWidget(self.nightstarttime)
        self.verticalLayout_14.addLayout(self.nightstarttime_box)
        self.nightendtime_box = QtWidgets.QHBoxLayout()
        self.nightendtime_box.setSpacing(0)
        self.nightendtime_box.setObjectName("nightendtime_box")
        self.nightendtime_label = QtWidgets.QLabel(self.night)
        self.nightendtime_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.nightendtime_label.setObjectName("nightendtime_label")
        self.nightendtime_box.addWidget(self.nightendtime_label)
        self.nightendtime = QtWidgets.QLabel(self.night)
        self.nightendtime.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.nightendtime.setObjectName("nightendtime")
        self.nightendtime_box.addWidget(self.nightendtime)
        self.verticalLayout_14.addLayout(self.nightendtime_box)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.gridLayout_10.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.night)
        self.holiday = QtWidgets.QWidget(self.request_pg)
        self.holiday.setStyleSheet("background-color:#02007a;\n"
"border-radius:30px;\n"
"")
        self.holiday.setObjectName("holiday")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.holiday)
        self.gridLayout_11.setContentsMargins(50, -1, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_4 = QtWidgets.QLabel(self.holiday)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/images/images/images/publicholiday.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_17.addWidget(self.label_4)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.holiday)
        self.label_15.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15)
        self.holidayprice_box = QtWidgets.QHBoxLayout()
        self.holidayprice_box.setSpacing(0)
        self.holidayprice_box.setObjectName("holidayprice_box")
        self.holidayprice_label = QtWidgets.QLabel(self.holiday)
        self.holidayprice_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.holidayprice_label.setObjectName("holidayprice_label")
        self.holidayprice_box.addWidget(self.holidayprice_label)
        self.holidayprice = QtWidgets.QLabel(self.holiday)
        self.holidayprice.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.holidayprice.setObjectName("holidayprice")
        self.holidayprice_box.addWidget(self.holidayprice)
        self.verticalLayout_16.addLayout(self.holidayprice_box)
        self.holidaystarttime_box = QtWidgets.QHBoxLayout()
        self.holidaystarttime_box.setSpacing(0)
        self.holidaystarttime_box.setObjectName("holidaystarttime_box")
        self.holidaystarttime_label = QtWidgets.QLabel(self.holiday)
        self.holidaystarttime_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.holidaystarttime_label.setObjectName("holidaystarttime_label")
        self.holidaystarttime_box.addWidget(self.holidaystarttime_label)
        self.holidaystarttime = QtWidgets.QLabel(self.holiday)
        self.holidaystarttime.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.holidaystarttime.setObjectName("holidaystarttime")
        self.holidaystarttime_box.addWidget(self.holidaystarttime)
        self.verticalLayout_16.addLayout(self.holidaystarttime_box)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.holidayendtime_label = QtWidgets.QLabel(self.holiday)
        self.holidayendtime_label.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.holidayendtime_label.setObjectName("holidayendtime_label")
        self.horizontalLayout_6.addWidget(self.holidayendtime_label)
        self.holidayendtime = QtWidgets.QLabel(self.holiday)
        self.holidayendtime.setStyleSheet("background-color: transparent;\n"
"font:  14pt \"Bell MT\";\n"
"color:#FFFFFF;\n"
"font-weight:bold;\n"
"border:transparent;")
        self.holidayendtime.setObjectName("holidayendtime")
        self.horizontalLayout_6.addWidget(self.holidayendtime)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.gridLayout_11.addLayout(self.verticalLayout_17, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.holiday)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.request_pg)
        self.record_pg = QtWidgets.QWidget()
        self.record_pg.setStyleSheet("background-color:#e5e5f1;")
        self.record_pg.setObjectName("record_pg")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.record_pg)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.record_header = QtWidgets.QLabel(self.record_pg)
        self.record_header.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"font-weight:bold;")
        self.record_header.setAlignment(QtCore.Qt.AlignCenter)
        self.record_header.setObjectName("record_header")
        self.verticalLayout_5.addWidget(self.record_header)
        self.record_box = QtWidgets.QWidget(self.record_pg)
        self.record_box.setStyleSheet("background-color:#02007a;\n"
"border-radius:4px;")
        self.record_box.setObjectName("record_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.record_box)
        self.gridLayout_3.setContentsMargins(50, 50, 50, 50)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.record_table = QtWidgets.QTableWidget(self.record_box)
        self.record_table.setStyleSheet("QHeaderView:section{\n"
"        \n"
"    background-color: rgb(229, 229, 241);\n"
"}\n"
"QTableWidget{    \n"
"    background-color: rgb(255, 255, 255);\n"
"    alternate-background-color: rgb(229, 229, 241);\n"
"}\n"
"")
        self.record_table.setAlternatingRowColors(True)
        self.record_table.setRowCount(0)
        self.record_table.setObjectName("record_table")
        self.record_table.setColumnCount(0)
        self.record_table.horizontalHeader().setDefaultSectionSize(150)
        self.record_table.horizontalHeader().setMinimumSectionSize(39)
        self.record_table.horizontalHeader().setStretchLastSection(True)
        self.record_table.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.record_table, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.record_box)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.record_pg)
        self.profile_pg = QtWidgets.QWidget()
        self.profile_pg.setStyleSheet("background-color:#e5e5f1;")
        self.profile_pg.setObjectName("profile_pg")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.profile_pg)
        self.gridLayout_13.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.widget = QtWidgets.QWidget(self.profile_pg)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.widget.setObjectName("widget")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.record_box_3 = QtWidgets.QWidget(self.widget)
        self.record_box_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.477091, x2:1, y2:0.494, stop:0 rgba(47, 0, 116, 255), stop:1 rgba(255, 212, 212, 255));\n"
"    border-bottom-left-radius:2px;\n"
"    border-bottom-right-radius:2px;\n"
"    border-top-left-radius:30px;\n"
"    border-top-right-radius:30px;")
        self.record_box_3.setObjectName("record_box_3")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.record_box_3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, -1, 50, -1)
        self.horizontalLayout_21.setSpacing(150)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(50)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.record_box_3)
        self.label_9.setStyleSheet("background-color: transparent;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/images/images/images/user.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.profile_header_2 = QtWidgets.QLabel(self.record_box_3)
        self.profile_header_2.setStyleSheet("background-color: transparent;\n"
"font:  40pt \"Bell MT\";\n"
"color: rgb(249, 206, 209);\n"
"font-weight:bold;")
        self.profile_header_2.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_header_2.setObjectName("profile_header_2")
        self.horizontalLayout_16.addWidget(self.profile_header_2)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_16)
        self.editprofile_btn_2 = QtWidgets.QPushButton(self.record_box_3)
        self.editprofile_btn_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.editprofile_btn_2.setStyleSheet("\n"
"    border-radius:8px;\n"
"    font: bold 20pt \"Bell MT\";\n"
"    border:1px solid grey;\n"
"    background-color:#02007a;\n"
"    color: rgb(255, 255, 255);\n"
"")
        self.editprofile_btn_2.setObjectName("editprofile_btn_2")
        self.horizontalLayout_21.addWidget(self.editprofile_btn_2)
        self.gridLayout_17.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.record_box_3, 0, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_38.setSpacing(6)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.username_label_2 = QtWidgets.QLabel(self.widget)
        self.username_label_2.setStyleSheet("background-color: transparent;\n"
"font: 20pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.username_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.username_label_2.setObjectName("username_label_2")
        self.verticalLayout_38.addWidget(self.username_label_2)
        self.username_edit_2 = QtWidgets.QTextEdit(self.widget)
        self.username_edit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  20pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(40, 40, 40);\n"
"border-radius:4px;")
        self.username_edit_2.setObjectName("username_edit_2")
        self.verticalLayout_38.addWidget(self.username_edit_2)
        self.verticalLayout_25.addLayout(self.verticalLayout_38)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.userEmail_label_2 = QtWidgets.QLabel(self.widget)
        self.userEmail_label_2.setStyleSheet("background-color: transparent;\n"
"font: 20pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.userEmail_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.userEmail_label_2.setObjectName("userEmail_label_2")
        self.verticalLayout_18.addWidget(self.userEmail_label_2)
        self.userEmail_edit_2 = QtWidgets.QTextEdit(self.widget)
        self.userEmail_edit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  20pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(40, 40, 40);\n"
"border-radius:4px;")
        self.userEmail_edit_2.setObjectName("userEmail_edit_2")
        self.verticalLayout_18.addWidget(self.userEmail_edit_2)
        self.verticalLayout_25.addLayout(self.verticalLayout_18)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.nric_label_2 = QtWidgets.QLabel(self.widget)
        self.nric_label_2.setStyleSheet("background-color: transparent;\n"
"font: 20pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.nric_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.nric_label_2.setObjectName("nric_label_2")
        self.verticalLayout_23.addWidget(self.nric_label_2)
        self.nric_edit_2 = QtWidgets.QTextEdit(self.widget)
        self.nric_edit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  20pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(40, 40, 40);\n"
"border-radius:4px;")
        self.nric_edit_2.setObjectName("nric_edit_2")
        self.verticalLayout_23.addWidget(self.nric_edit_2)
        self.verticalLayout_25.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.phone_label_2 = QtWidgets.QLabel(self.widget)
        self.phone_label_2.setStyleSheet("background-color: transparent;\n"
"font: 20pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.phone_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.phone_label_2.setObjectName("phone_label_2")
        self.verticalLayout_24.addWidget(self.phone_label_2)
        self.phone_edit_2 = QtWidgets.QTextEdit(self.widget)
        self.phone_edit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  20pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(40, 40, 40);\n"
"border-radius:4px;")
        self.phone_edit_2.setObjectName("phone_edit_2")
        self.verticalLayout_24.addWidget(self.phone_edit_2)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.gridLayout_16.addLayout(self.verticalLayout_25, 0, 0, 1, 1)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.address_label_2 = QtWidgets.QLabel(self.widget)
        self.address_label_2.setStyleSheet("background-color: transparent;\n"
"font: 20pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.address_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.address_label_2.setObjectName("address_label_2")
        self.verticalLayout_26.addWidget(self.address_label_2)
        self.address_edit_2 = QtWidgets.QTextEdit(self.widget)
        self.address_edit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  20pt \"Bell MT\";\n"
"border:1px solid #c8c8c8;\n"
"color: rgb(40, 40, 40);\n"
"border-radius:4px;")
        self.address_edit_2.setObjectName("address_edit_2")
        self.verticalLayout_26.addWidget(self.address_edit_2)
        self.gridLayout_16.addLayout(self.verticalLayout_26, 0, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.profile_pg)
        self.search_pg2 = QtWidgets.QWidget()
        self.search_pg2.setObjectName("search_pg2")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.search_pg2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.widget_5 = QtWidgets.QWidget(self.search_pg2)
        self.widget_5.setStyleSheet("background-color: rgb(2, 0, 122);\n"
"    border-radius: 8px;")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.back_btn = QtWidgets.QPushButton(self.widget_5)
        self.back_btn.setStyleSheet("background-color: transparent;")
        self.back_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-back-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon9)
        self.back_btn.setIconSize(QtCore.QSize(50, 50))
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_17.addWidget(self.back_btn)
        self.clinicname_label = QtWidgets.QLabel(self.widget_5)
        self.clinicname_label.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.clinicname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.clinicname_label.setObjectName("clinicname_label")
        self.horizontalLayout_17.addWidget(self.clinicname_label)
        self.horizontalLayout_17.setStretch(1, 1)
        self.gridLayout_20.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.search_pg2)
        self.widget_4.setStyleSheet("background-color: rgb(2, 0, 122);\n"
"    border-radius: 8px;")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.clinicimage = QtWidgets.QLabel(self.widget_4)
        self.clinicimage.setText("")
        self.clinicimage.setObjectName("clinicimage")
        self.horizontalLayout_11.addWidget(self.clinicimage)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.about_us_3 = QtWidgets.QLabel(self.widget_4)
        self.about_us_3.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.about_us_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.about_us_3.setObjectName("about_us_3")
        self.verticalLayout_27.addWidget(self.about_us_3)
        self.clinicdetail_label = QtWidgets.QTextEdit(self.widget_4)
        self.clinicdetail_label.setStyleSheet("background-color: transparent;\n"
"font: 18pt \"Bell MT\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.clinicdetail_label.setReadOnly(True)
        self.clinicdetail_label.setObjectName("clinicdetail_label")
        self.verticalLayout_27.addWidget(self.clinicdetail_label)
        self.viewmap = QtWidgets.QPushButton(self.widget_4)
        self.viewmap.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"font-weight:bold;")
        self.viewmap.setObjectName("viewmap")
        self.verticalLayout_27.addWidget(self.viewmap)
        self.horizontalLayout_11.addLayout(self.verticalLayout_27)
        self.gridLayout_19.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.widget_4, 1, 0, 1, 1)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.ourdoctor = QtWidgets.QLabel(self.search_pg2)
        self.ourdoctor.setStyleSheet("background-color: transparent;\n"
"font: 75 24pt \"Bell MT\";\n"
"color: rgb(0, 0, 0);\n"
"font-weight:bold;")
        self.ourdoctor.setAlignment(QtCore.Qt.AlignCenter)
        self.ourdoctor.setObjectName("ourdoctor")
        self.verticalLayout_28.addWidget(self.ourdoctor)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.doctor1 = QtWidgets.QWidget(self.search_pg2)
        self.doctor1.setStyleSheet("background-color:#02007a;\n"
"border-radius:30px;\n"
"")
        self.doctor1.setObjectName("doctor1")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.doctor1)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.doctorimg1 = QtWidgets.QLabel(self.doctor1)
        self.doctorimg1.setText("")
        self.doctorimg1.setObjectName("doctorimg1")
        self.gridLayout_22.addWidget(self.doctorimg1, 0, 0, 1, 1)
        self.doctordetail_label1 = QtWidgets.QLabel(self.doctor1)
        self.doctordetail_label1.setObjectName("doctordetail_label1")
        self.doctordetail_label1.setStyleSheet("color: rgb(255, 255, 255);\n"
         "font:  14pt \"Bell MT\";\n"
         "font-weight:bold;")
        self.gridLayout_22.addWidget(self.doctordetail_label1, 0, 1, 1, 1)
        self.horizontalLayout_14.addWidget(self.doctor1)
        self.doctor3 = QtWidgets.QWidget(self.search_pg2)
        self.doctor3.setStyleSheet("background-color:#02007a;\n"
"border-radius:30px;\n"
"")
        self.doctor3.setObjectName("doctor3")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.doctor3)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.doctorimg3 = QtWidgets.QLabel(self.doctor3)
        self.doctorimg3.setText("")
        self.doctorimg3.setObjectName("doctorimg3")
        self.gridLayout_21.addWidget(self.doctorimg3, 1, 0, 1, 1)
        self.doctordetail_label3 = QtWidgets.QLabel(self.doctor3)
        self.doctordetail_label3.setObjectName("doctordetail_label3")
        self.doctordetail_label3.setStyleSheet("color: rgb(255, 255, 255);\n"
                     "font:  14pt \"Bell MT\";\n"
                     "font-weight:bold;")
        self.gridLayout_21.addWidget(self.doctordetail_label3, 1, 1, 1, 1)
        self.horizontalLayout_14.addWidget(self.doctor3)
        self.doctor2 = QtWidgets.QWidget(self.search_pg2)
        self.doctor2.setStyleSheet("background-color:#02007a;\n"
"border-radius:30px;\n"
"")
        self.doctor2.setObjectName("doctor2")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.doctor2)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.doctorimg2 = QtWidgets.QLabel(self.doctor2)
        self.doctorimg2.setText("")
        self.doctorimg2.setObjectName("doctorimg2")
        self.gridLayout_23.addWidget(self.doctorimg2, 0, 0, 1, 1)
        self.doctordetail_label2 = QtWidgets.QLabel(self.doctor2)
        self.doctordetail_label2.setObjectName("doctordetail_label2")
        self.doctordetail_label2.setStyleSheet("color: rgb(255, 255, 255);\n"
                     "font:  14pt \"Bell MT\";\n"
                     "font-weight:bold;")
        self.gridLayout_23.addWidget(self.doctordetail_label2, 0, 1, 1, 1)
        self.horizontalLayout_14.addWidget(self.doctor2)
        self.verticalLayout_28.addLayout(self.horizontalLayout_14)
        self.gridLayout_24.addLayout(self.verticalLayout_28, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_pg2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_6, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.hide_btn_2.clicked['bool'].connect(self.sidebar.setVisible) # type: ignore
        self.hide_btn.clicked['bool'].connect(self.sidebar_2.setVisible) # type: ignore
        self.hide_btn_2.clicked['bool'].connect(self.sidebar_2.setHidden) # type: ignore
        self.hide_btn.clicked['bool'].connect(self.sidebar.setHidden) # type: ignore
        self.home_btn.toggled['bool'].connect(self.home_btn_2.setChecked) # type: ignore
        self.search_btn.toggled['bool'].connect(self.search_btn_2.setChecked) # type: ignore
        self.request_btn.toggled['bool'].connect(self.request_btn_2.setChecked) # type: ignore
        self.record_btn.toggled['bool'].connect(self.record_btn_2.setChecked) # type: ignore
        self.record_btn_2.toggled['bool'].connect(self.record_btn.setChecked) # type: ignore
        self.request_btn_2.toggled['bool'].connect(self.request_btn.setChecked) # type: ignore
        self.search_btn_2.toggled['bool'].connect(self.search_btn.setChecked) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.home_btn.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.app_name.setText(_translate("MainWindow", "Call A Doctor"))
        self.hide_btn.setText(_translate("MainWindow", "   Hide"))
        self.home_btn.setText(_translate("MainWindow", "   Home"))
        self.search_btn.setText(_translate("MainWindow", "   Search"))
        self.request_btn.setText(_translate("MainWindow", "   Appoinment"))
        self.record_btn.setText(_translate("MainWindow", "   Record"))
        self.profile_btn.setText(_translate("MainWindow", "   Profile"))
        self.quit_btn.setText(_translate("MainWindow", "   Quit"))
        self.home_header_3.setText(_translate("MainWindow", "Welcome to Call A Doctor"))
        self.home_header_4.setText(_translate("MainWindow", "We Provide 24 hours Professional Medical Care to Your Doorstep"))
        self.about_us_2.setText(_translate("MainWindow", "About Us"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bell MT\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Our experience has shown us that treating those who need medical  services  in  their  home  setting  improves  health outcomes,  reduces  patient  stress,  and  provides  comfort. The health of our patients is always  our  priority. Our doctors work  around  the clock to provide the very best at home to patients. Our doctors treat children, adults, and the elderly with care and compassion. Whether you are at home, in a hotel or in an aged care facility, wherever you are, we can treat you.</span></p></body></html>"))
        self.ourpartner_2.setText(_translate("MainWindow", "Our Partners"))
        item = self.search_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Clinic\'s Name"))
        item = self.search_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address"))
        self.search_lineedit_6.setPlaceholderText(_translate("MainWindow", "Clinic\'s Name, Address..."))
        self.request_header_2.setText(_translate("MainWindow", "Search Clinic"))
        self.request_header.setText(_translate("MainWindow", "Appoinment for a doctor?"))
        self.request_boxheader.setText(_translate("MainWindow", "Call A Doctor offers a variety of packages, \n"
"tailored to fit your needs at affordable prices."))
        self.date_label.setText(_translate("MainWindow", "Date:"))
        self.time_label.setText(_translate("MainWindow", "Time:"))
        self.requestdoctor_btn.setText(_translate("MainWindow", "Appoinment"))
        self.label.setText(_translate("MainWindow", "Day Package"))
        self.dayprice_label.setText(_translate("MainWindow", "Price:"))
        self.day_price.setText(_translate("MainWindow", "RM200"))
        self.daystarttime_label.setText(_translate("MainWindow", "Start Time:"))
        self.daystarttime.setText(_translate("MainWindow", "08:00"))
        self.dayendtime_label.setText(_translate("MainWindow", "End Time:"))
        self.dayendtime.setText(_translate("MainWindow", "20:00"))
        self.label_8.setText(_translate("MainWindow", "Night Package"))
        self.nightprice_label.setText(_translate("MainWindow", "Price:"))
        self.nightprice.setText(_translate("MainWindow", "RM300"))
        self.nightstarttime_label.setText(_translate("MainWindow", "Start Time:"))
        self.nightstarttime.setText(_translate("MainWindow", "20:00"))
        self.nightendtime_label.setText(_translate("MainWindow", "End Time:"))
        self.nightendtime.setText(_translate("MainWindow", "08:00"))
        self.label_15.setText(_translate("MainWindow", "Public Holiday Package"))
        self.holidayprice_label.setText(_translate("MainWindow", "Price:"))
        self.holidayprice.setText(_translate("MainWindow", "RM500"))
        self.holidaystarttime_label.setText(_translate("MainWindow", "Start Time:"))
        self.holidaystarttime.setText(_translate("MainWindow", "00:00"))
        self.holidayendtime_label.setText(_translate("MainWindow", "End Time:"))
        self.holidayendtime.setText(_translate("MainWindow", "24:00"))
        self.record_header.setText(_translate("MainWindow", "Record"))
        self.profile_header_2.setText(_translate("MainWindow", "Welcome to Profile Page"))
        self.editprofile_btn_2.setText(_translate("MainWindow", "Edit"))
        self.username_label_2.setText(_translate("MainWindow", "Username"))
        self.userEmail_label_2.setText(_translate("MainWindow", "E-mail"))
        self.nric_label_2.setText(_translate("MainWindow", "NRIC"))
        self.nric_edit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bell MT\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.phone_label_2.setText(_translate("MainWindow", "Phone Number"))
        self.phone_edit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bell MT\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.address_label_2.setText(_translate("MainWindow", "Address"))
        self.clinicname_label.setText(_translate("MainWindow", "Clinic Name"))
        self.about_us_3.setText(_translate("MainWindow", "About Us"))
        self.clinicdetail_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bell MT\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Our experience has shown us that treating those who need medical  services  in  their  home  setting  improves  health outcomes,  reduces  patient  stress,  and  provides  comfort. The health of our patients is always  our  priority. Our doctors work  around  the clock to provide the very best at home to patients. Our doctors treat children, adults, and the elderly with care and compassion. Whether you are at home, in a hotel or in an aged care facility, wherever you are, we can treat you.</span></p></body></html>"))
        self.viewmap.setText(_translate("MainWindow", "View In Google Map"))
        self.ourdoctor.setText(_translate("MainWindow", "Our Doctors"))
        self.doctordetail_label1.setText(_translate("MainWindow", "TextLabel"))
        self.doctordetail_label3.setText(_translate("MainWindow", "TextLabel"))
        self.doctordetail_label2.setText(_translate("MainWindow", "TextLabel"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
